name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --features cbindgen
      - run: cargo test
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - name: Test C++ example
        run: |
          cd examples
          cmake -B build
          cmake --build build
          ./build/main

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.82
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --features cbindgen
      - run: cargo test
      - name: Test C++ example
        run: |
          cd examples
          cmake -B build
          cmake --build build
          ./build/main
